theme: jekyll-theme-leap-day

title: "Liberal Arts Computing Curricula"
description: "SIGCSE 2020 Pre-Symposium Event proposed by the SIGCSE Committee on Computing Education in Liberal Arts Colleges"
