theme: jekyll-theme-leap-day

title: "Liberal Arts Computing Curricula: Innovations, Challenges, and Opportunities"
description: "SIGCSE 2019 Pre-Symposium Event proposed by the SIGCSE Committee on Computing Education in Liberal Arts Colleges"
